services:
  backend:
    build: .
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: fin-matcher
      DB_HOST: ${DB_HOST}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
    ports:
      - "127.0.0.1:8001:8000"
    networks:
      - ci-net

networks:
  ci-net:
    external: true
